### ISSUE TITLE
[Pull Request] Snips, Notes, Filters

### ISSUE THREAD

**Issue by ghost** [AvinashReddy3108/PaperplaneRemix#15]
Global and only for specific chat notes
.snip save snip (can be file, link or a paragraph)
.rmsnip remove snip
.snips list of snips

.notes
.save (can be file, link or a paragraph)
"#" gets note

.filter save filter
.stop stop a filter
.filters shows all filters in chat

**Comment by ghost** [comment]
Add SpamWatch bans please

**Comment by AvinashReddy3108** [comment]
@interastra Sure, I'm focused more on the new Telegram changes (Anonymous Admins) and the breaking changes in Telethon 1.17.x right now..

This will be added too, would be a nice addition to the blacklists we currently have here.

**Comment by ghost** [comment]
can not add more than 3 gblacklists, and bot's in-tg wiki does not match with commands
I'm on tg again, @YNSparkle
